In [1]:
from model.QBVM import QuasiBayesianVineRegression

In [2]:
from sklearn.datasets import load_wine
from sklearn.preprocessing import MinMaxScaler

feat, target = load_wine(return_X_y=True)

feat = MinMaxScaler().fit_transform(feat)[:2]
target = MinMaxScaler().fit_transform(target.reshape(-1, 1))[:2]
feat, target

(array([[0.84210526, 0.1916996 , 0.57219251, 0.25773196, 0.61956522,
         0.62758621, 0.57383966, 0.28301887, 0.59305994, 0.37201365,
         0.45528455, 0.97069597, 0.56134094],
        [0.57105263, 0.2055336 , 0.4171123 , 0.03092784, 0.32608696,
         0.57586207, 0.51054852, 0.24528302, 0.27444795, 0.26450512,
         0.46341463, 0.78021978, 0.55064194]]),
 array([[0.],
        [0.]]))

In [3]:
model = QuasiBayesianVineRegression()
model.fit(feat, target[:len(feat)])

#predictions = model.predict(feat)

model.predict(feat[2])

x_density (2,)
x_distribution (2,)
x_distribution_n (2,)
y_distribution (2,)
Samples: (2,) (1,)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

In [5]:
feat[2]

array([0.56052632, 0.3201581 , 0.70053476, 0.41237113, 0.33695652,
       0.62758621, 0.61181435, 0.32075472, 0.75709779, 0.37542662,
       0.44715447, 0.6959707 , 0.64693295])

In [1]:
model.predict(feat[2])

NameError: name 'model' is not defined